server:
  port: 8022

spring:
  application:
    # 应用程序名字
    name: springcloud-porducta

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      # 注册中心路径:如果服务中心设置了context-path要添加context-path路径
      defaultZone: http://localhost:8001/springeureka/eureka